# -*- coding: utf-8 -*-
"""PORTFOLIO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3Fqid2wT0QUD-8y4AFHE8YA2DJca3JN
"""

import torch
torch.cuda.is_available()

!pip install -q transformers accelerate bitsandbytes
!pip install -q gradio

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

print("Granite Model Loaded ✅")

def generate_html(user_prompt):

    full_prompt = f"""
    Generate ONLY valid complete HTML5 code.
    Include CSS inside <style> tag.
    Do not explain anything.
    User requirement:
    {user_prompt}
    """

    inputs = tokenizer(full_prompt, return_tensors="pt").to("cuda")

    outputs = model.generate(
        **inputs,
        max_new_tokens=600,
        temperature=0.6
    )

    result = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return result

import gradio as gr

with gr.Blocks() as demo:

    gr.Markdown("# 🚀 HTML Quick-Styler")

    user_input = gr.Textbox(
        label="Describe Your Website",
        placeholder="Example: Modern dark theme portfolio for UI designer"
    )

    output_html = gr.HTML()

    generate_button = gr.Button("Generate Website")

    generate_button.click(
        generate_html,
        inputs=user_input,
        outputs=output_html
    )

demo.launch(share=True)